### ISSUE TITLE
エンドポイントのAPI設計

### ISSUE THREAD

**Issue by oohira** [kaigi-no-owari/fukase#4]
スケジュール情報をやりとりするためのAPI仕様を決める。
## スケジュール登録API
- POST /api/meetings
  - ミーティングの一覧を登録する

``` js
[
    {
        "room_id": "A",
        "title": "MTGタイトル",
        "description": "MTG詳細情報",
        "start_at": "2016-06-21T01:00:00.000Z",
        "end_at": "2016-06-21T02:00:00.000Z"
    },
    ...
    (繰り返し)
]
```
- 差分更新は特にせずDBをまるごと削除して新しいデータで置き換える
- `room_id` は会議室を識別する primary key だが、値のセマンティクスはサーバー側では管理しない（どの会議室がどんなIDをもつかはスケジュールデータの登録側で管理）
- `room_id`, `start_at`, `end_at` は必須
## スケジュール取得API
- GET /api/meetings
  - 全会議室のミーティング一覧を取得する
- GET /api/meetings/{room_id}
  - 指定した会議室のミーティング一覧を取得する

``` js
[
    {
        "room_id": "A",
        "title": "MTGタイトル",
        "description": "MTG詳細情報",
        "start_at": "2016-06-21T01:00:00.000Z",
        "end_at": "2016-06-21T02:00:00.000Z"
    },
    ...
    (繰り返し)
]
```
- `from` と `to` を指定することで範囲を制限できる（一方だけでも両方でも指定できる）
  - 例： /api/meetings/A?from=2016-06-21T01:00:00.000Z&to=2016-06-21T01:00:00.000Z
- `from` を省略した場合は、現在日時が指定されているとみなす
- `limit` を指定することで取得する最大数を制限できる（開始日時の古い順）
  - 例：/api/meetings/A?limit=1

**Comment by oohira** [comment]
@radiocat 実装は個別のチケットで進めるとして、API仕様に問題がなさそうかだけ確認をお願いします。

**Comment by radiocat** [comment]
`room_id` ⇒会議室というより施設に1〜の番号が振られている（プロジェクタとかVexも）。60ぐらいまであるが、空き番号もありそう。
`description` 施設一覧には表示されないのでできれば無しで。
`title` これは取得可能だが、思った以上にDOM解析に時間がかかりそう。セキュリティ的な懸念もあるし無しのほうが現実的かも。

**Comment by radiocat** [comment]
あと、当日分のみを取得します。翌日以降も頑張れば取れるけど、これもかなり時間がかかるし、今回の目的では不要ですよね？

**Comment by oohira** [comment]
> description 施設一覧には表示されないのでできれば無しで。
> title これは取得可能だが、思った以上にDOM解析に時間がかかりそう。

いずれもオプション項目なので、単に送信しないようにしてもらえばOKです。

> あと、当日分のみを取得します。

問題ないです。
